"""Initial migration

Revision ID: 613e217d6093
Revises: e6b842d69531
Create Date: 2024-05-22 21:51:25.221529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613e217d6093'
down_revision = 'e6b842d69531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_column('content')
        batch_op.drop_column('author')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('author',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
